services:
  redis:
    image: redis:7-alpine
    container_name: goodhamburger_redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - goodhamburger_network

  api:
    build: .
    container_name: goodhamburger_api
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - goodhamburger_network

volumes:
  redis_data:

networks:
  goodhamburger_network:
    driver: bridge
